		
--		SELECT * FROM t_cd WHERE CD_NM LIKE '%펫룸%';
--		SELECT * FROM T_RSVT WHERE RSVT_NO = '202307210283';

		-- Index: 98

      SET @SLNG_YMD = '20230821';
      SET @RT_CD = 'RTWDCJ';
      SET @DPTM = '1500';
      SET @SHIP_CD = 'SHP02';
      SET @CBN_CD = 'CB310';
      SET @SWAY_CD = (SELECT B.SWAY_CD FROM t_rt B WHERE B.RT_CD = @RT_CD);      
		-- CBS00 CBF00 CB102 CB1W2 CB115 CBP15 CB204 CBC00 CBC01 CBP10 CB210 CB310 CBD00 		골드
		-- CBF00 CB104 CB102 CB101 CBP04 CBP10 CB220 CB210 CB310 CBD00 CBD10 						실클
		-- CBV00 CBF00 CB101 CB102 CB104 CB105 CBP15 CB112 CB114 CBB00 CBP10 CB210 CB310 CBD00 블펄
		
		-- 채널별 승선권 갯수
		SELECT  B.PREO_CHNL, B.RSVT_STAT, COUNT(1) FROM T_RSVT A  JOIN t_ptckt B
		ON A.RSVT_NO = B.RSVT_NO
		AND A.RT_CD = B.RT_CD
		AND A.MNYSCTN_SN = B.MNYSCTN_SN
		WHERE A.SLNG_YMD = @SLNG_YMD
		AND A.RT_CD = @RT_CD	
		AND A.DPTM = @DPTM
		AND A.SHIP_CD = @SHIP_CD		
		AND B.RSVT_STAT IN ('TSRVS', 'TSMKV', 'TSTKT', 'TSLSS')
		AND B.CBN_CD = @CBN_CD
		AND B.VLD_YN = 'Y'
		GROUP BY B.PREO_CHNL, B.RSVT_STAT;
		
		SELECT * FROM T_SLNG_SCHDL_CBN
		WHERE SLNG_YMD = @SLNG_YMD
		AND SWAY_CD = @SWAY_CD
		AND SLNG_TM = @DPTM
		AND SHIP_CD = @SHIP_CD
		AND CBN_CD = @CBN_CD;
		
		
		SELECT * FROM T_SLNG_SCHDL_CBN_CNT
		WHERE SLNG_YMD = @SLNG_YMD
		AND RT_CD = @RT_CD
		AND DPTM = @DPTM
		AND SHIP_CD = @SHIP_CD
		AND CBN_CD = @CBN_CD;
		
		SELECT *
		FROM t_slng_schdl_seat
		WHERE SLNG_YMD = @SLNG_YMD AND SWAY_CD = @SWAY_CD AND SLNG_TM = @DPTM AND SHIP_CD = @SHIP_CD AND CBN_CD = @CBN_CD 
--		AND MKRV_CNT  = 1 AND RMN_CNT = 1
--		AND CBN_NO IN ('6217') -- , '6220', '6221')
--		AND RMN_CNT > 0;
		ORDER BY CBN_NO, SEAT_NO;
		
		SELECT * FROM T_SLNG_SCHDL_PREO
		WHERE SLNG_YMD = @SLNG_YMD
		AND RT_CD = @RT_CD
		AND DPTM = @DPTM
		AND SHIP_CD = @SHIP_CD
		AND CBN_CD = @CBN_CD;
		
		-- 객실의 승선권이 얼마나 있는지?
		SELECT B.CBN_NO, B.RSVT_STAT, SUM(B.OCC_NOPE), COUNT(1) FROM T_RSVT A  JOIN t_ptckt B
		ON A.RSVT_NO = B.RSVT_NO
		AND A.RT_CD = B.RT_CD
		AND A.MNYSCTN_SN = B.MNYSCTN_SN
		WHERE A.SLNG_YMD = @SLNG_YMD
		AND A.RT_CD = @RT_CD
		AND A.DPTM = @DPTM
		AND A.SHIP_CD = @SHIP_CD
		AND B.RSVT_STAT IN ( 'TSRVS', 'TSTKT', 'TSMKV', 'TSLSS')
		AND B.CBN_CD IN (@CBN_CD)
		AND B.VLD_YN = 'Y'
		GROUP BY B.CBN_NO, B.RSVT_STAT
		ORDER BY CBN_NO, B.RSVT_STAT;
		
		-- 좌석 있을때 확인하는 쿼리
		SELECT B.CBN_NO, B.NM, B.RSVT_STAT, B.SEAT_NO, B.OCC_NOPE, B.BRDT, B.PREO_CHNL
		FROM T_RSVT A  JOIN t_ptckt B
			ON A.RSVT_NO = B.RSVT_NO
			AND A.RT_CD = B.RT_CD
			AND A.MNYSCTN_SN = B.MNYSCTN_SN
		WHERE A.SLNG_YMD = @SLNG_YMD
		AND A.RT_CD = @RT_CD
		AND A.DPTM = @DPTM
		AND A.SHIP_CD = @SHIP_CD
		AND B.RSVT_STAT IN ( 'TSRVS', 'TSTKT', 'TSMKV')
		AND B.CBN_CD IN (@CBN_CD)
--		AND B.CBN_NO = '6221'
--		AND B.SEAT_NO IN ('A09')
		AND B.VLD_YN = 'Y'
		GROUP BY B.CBN_NO, B.SEAT_NO
		ORDER BY CBN_NO, SEAT_NO;
		
		
		-- 예약상태, 선점채널 로 실제 승선권 조회
		SELECT *
		FROM t_ptckt 
		WHERE SLNG_YMD = @SLNG_YMD
		AND RT_CD = @RT_CD
		AND DPTM = @DPTM
		AND SHIP_CD = @SHIP_CD
		AND RSVT_STAT IN ('TSRVS')
		AND PREO_CHNL = 'PLHP0'
		AND CBN_CD IN (@CBN_CD)
--		AND VLD_YN = 'Y'
--		AND CBN_NO = 5301
		ORDER BY CBN_NO, SEAT_NO;
		





